# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('edad', models.IntegerField()),
                ('estatura', models.DecimalField(decimal_places=4, max_digits=1000)),
                ('fecha_nacimiento', models.DateField(default=django.utils.timezone.now)),
                ('hora_nacimiento', models.TimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'pruebas_persona',
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
