# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estado_civil',
            field=models.IntegerField(choices=[(1, 'Soltero'), (2, 'Casado'), (3, 'Viudo'), (4, 'Divorciado')], default=1),
        ),
    ]
