# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='descripcion',
            field=models.CharField(default='', max_length=250),
        ),
    ]
