# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_departamento_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('turno', models.IntegerField(choices=[(1, 'MATUTINO'), (2, 'VESPERTINO'), (3, 'NOCTURNO')], default=1)),
                ('fecha_hora_inicio_turno', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Departamento')),
            ],
            options={
                'db_table': 'pruebas_empleado',
            },
        ),
    ]
